# Generated by Django 3.2.16 on 2023-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YamapCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('proof_link', models.URLField(max_length=2048, verbose_name='Ссылка в яндекс картах накомпанию')),
                ('adress', models.CharField(blank=True, max_length=256, verbose_name='Адресс')),
                ('category', models.CharField(blank=True, max_length=256, verbose_name='Адресс')),
                ('latitude', models.CharField(blank=True, max_length=256, verbose_name='Адресс')),
                ('longitude', models.CharField(blank=True, max_length=256, verbose_name='Адресс')),
                ('date_time_polled', models.DateField(blank=True, null=True, verbose_name='Дата последнего опроса компании')),
            ],
        ),
    ]
